[[lines_present]]
file = "~/.bashrc"
lines = "export SHELL=/bin/bash"

[[lines_present]]
file = "~/.bashrc"
lines = "export EDITOR=hx"


[[key_value_present]]
file = "test.json"
key1.key2.key3="value"


[[key_value_present]]
file = "test.toml"
inline_table.key="value"


[[key_value_present.table]]
file = "test.toml"
key="value"
