[[key_value_present]]
file = "pyproject.toml"

[key_value_present.key.tool.mypy]
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true

[[entry_present]]
file = ".pre-commit-config.yaml"
entry.repos = [
    { repo = "local", hooks = [
        { id = "mypy", name = "mypy", language = "system", entry = "poetry run mypy dvb", pass_filenames = false, always_run = true },
    ] },
    { repo = "local", hooks = [
        { id = "mypy_on_tests", name = "mypy", language = "system", entry = "poetry run mypy tests", pass_filenames = false, always_run = true },
    ] },
]

[[lines_present]]
file = ".gitignore"
lines = ".mypy_cache"
