[[file_copied]]
# copy from url
destination = "output/rust-logo.svg"
source = "https://www.rust-lang.org/logos/rust-logo-blk.svg"

[[file_copied]]
# copy from path relative to the current file
destination = "output/python-logo.svg"
source = "config:python-logo.svg"

[[file_present]]
file = "output/rust-logo.svg"
fixable = false

[[file_present]]
file = "output/python-logo.svg"
fixable = false
