[check-config]
additional_checks = ["./flake8.toml"]

["test/absent.toml".file_absent]

["test/present.toml".file_present]

["test/present.toml".lines_present]
__lines__ = "present"

["test/present.toml".lines_absent]
__lines__ = """\
    multi
    line"""

["test/present1.toml".key_value_regex_match]
integer = "[0-9]*"
double = "[0-9]*\\.[0-9]*"

["test/present1.toml".key_value_present]
key = "value"

[["test/present1.toml".key_value_present.array]]
key1 = "value"

[["test/present1.toml".key_value_present.array]]
key2 = "value2"

["test/Cargo.toml".key_value_present.dependencies]
bar = "1.0"

["test/Cargo.toml".key_absent.dependencies.foo]

["test/Cargo.toml".key_absent.dependencies]
test = "remove"
