[nitpick]
additional_styles = ["./flake8.toml"]

["test/absent.toml".file_absent]

["test/present.toml".file_present]

["test/present.toml".lines_present]
__lines__ = "present"

["test/present.toml".lines_absent]
__lines__ = "absent"

["test/present1.toml".entry_present]
key = "value"

[["test/present1.toml".entry_present.array]]
key1 = "value"

[["test/present1.toml".entry_present.array]]
key2 = "value2"

["test/Cargo.toml".entry_present.dependencies]
bar = "1.0"

["test/Cargo.toml".entry_absent.dependencies.foo]

["test/Cargo.toml".entry_absent.dependencies]
test = "remove"
