[nitpick]
path_key = "__path__"                 #efault
status_key = "__status__"             #default
top_key = "__top__"                   #default
additional_styles = ["./flake8.toml"]

[[__file__]]
__path__ = "test/absent.toml"
__check__ = "file_absent"

[[__file__]]
__path__ = "test/present.toml"
__check__ = "file_present"

[[__file__]]
__path__ = "test/present.toml"
__check__ = "lines_present"
__lines__ = "present"

[[__file__]]
__path__ = "test/present.toml"
__check__ = "lines_absent"
__lines__ = "absent"

[[__top__]]
__path__ = "test/present1.toml"
__check__ = "key_present"
key = "value"

[[dependencies]]
__path__ = "test/Cargo.toml"
__check__ = "key_present"
bar = "1.0"
